apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: nestcloud-kubernetes-example
  name: nestcloud-kubernetes-example
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestcloud-kubernetes-example
  template:
    metadata:
      labels:
        app: nestcloud-kubernetes-example
    spec:
      containers:
        - image: nestcloud/nestcloud-kubernetes-example:1.1.2
          imagePullPolicy: IfNotPresent
          name: proxy
          resources: {}
          env:
            - name: NODE_ENV
              value: production
            - name: RUNTIME
              value: kubernetes
          volumeMounts:
            - mountPath: /opt/app/build/config.yaml
              name: volume-config
              subPath: config.yaml
      volumes:
        - configMap:
            items:
              - key: config.yaml
                path: config.yaml
            name: nestcloud-kubernetes-example-conf
          name: volume-config
      serviceAccountName: nestcloud-kubernetes-example-account
